languageCode = "en-us"
title = "Lucy Whalley"
baseURL = "https://lucydot.github.io/"
theme = "code-editor"
googleAnalytics = "UA-125953365-1"

[blackfriday]
    fractions = false

[params]
    author = "Lucy Whalley"
    locale = "en-US"
    DateForm = "2.1.2006"
